### ISSUE TITLE
Create poster for event.

### ISSUE THREAD

**Issue by denysdovhan** [nodeschool/chernivtsi#5]
So we should draw poster for our event.

**Comment by denysdovhan** [comment]
# Our poster

Now we have cool poster for our future events. Don't tell us that there are mistakes — we know it.

![nodeschool](https://cloud.githubusercontent.com/assets/3459374/10561493/61849658-7533-11e5-815c-c65bef09920d.png)

**Comment by sudodoki** [comment]
:clap:
